version: 2.1
jobs:
  test:
    docker:
      - image: "golang:1.13"
    steps:
      - checkout
      - run: go test ./...

  lint:
    docker:
      - image: "golang:1.13"
    steps:
      - checkout
      - run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - run: |
          go build .
          golangci-lint run

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: "Go Unit Tests"
      - lint:
          name: "Lint"
